"""Preset-driven shot plan contracts and compiler."""

from shorts_engine.shot_plans.benchmarks import (
    TALL_OWL_BENCHMARK_ID,
    TALL_OWL_BRAND_INPUT,
    TALL_OWL_FIRST_FRAME_REVIEW_GUIDANCE,
    TALL_OWL_PRODUCT_INPUT,
    TALL_OWL_REFERENCE_ASSETS,
    build_tall_owl_first_frame_review_payload,
    compile_tall_owl_benchmark_shot_plan,
)
from shorts_engine.shot_plans.approvals import apply_ref_pack_approvals
from shorts_engine.shot_plans.compiler import compile_shot_plan
from shorts_engine.shot_plans.contracts import (
    ApprovedStoryboardBoard,
    BrandRuntimeInput,
    CompiledShotPlan,
    FirstFrameApprovalGate,
    FirstFramePromptInputs,
    FirstFrameReferenceAsset,
    FirstFrameReviewPayload,
    FirstFrameReviewShot,
    FirstFrameReviewStatus,
    PresetShotTemplate,
    PresetSpec,
    PresetVersion,
    ProductConceptInput,
    ReferenceRequirement,
    ShotPlan,
    ShotSpec,
    ShotStatus,
    StoryboardBoardSpec,
    StoryboardDeckSpec,
    ShotTakeRequest,
    TakeGenerationDefaults,
    TakeRequestStatus,
)
from shorts_engine.shot_plans.presets import (
    FLAGSHIP_PRESET_ID,
    FLAGSHIP_PRESET_VERSION,
    PREMIUM_PRODUCT_MACRO_REVEAL_PACKSHOT,
    get_shot_plan_preset,
    list_shot_plan_presets,
)
from shorts_engine.shot_plans.review_payload import (
    DEFAULT_FIRST_FRAME_REVIEW_GUIDANCE,
    build_first_frame_review_payload,
)

__all__ = [
    "FLAGSHIP_PRESET_ID",
    "FLAGSHIP_PRESET_VERSION",
    "PREMIUM_PRODUCT_MACRO_REVEAL_PACKSHOT",
    "ApprovedStoryboardBoard",
    "BrandRuntimeInput",
    "CompiledShotPlan",
    "DEFAULT_FIRST_FRAME_REVIEW_GUIDANCE",
    "apply_ref_pack_approvals",
    "FirstFrameApprovalGate",
    "FirstFramePromptInputs",
    "FirstFrameReferenceAsset",
    "FirstFrameReviewPayload",
    "FirstFrameReviewShot",
    "FirstFrameReviewStatus",
    "PresetShotTemplate",
    "PresetSpec",
    "PresetVersion",
    "ProductConceptInput",
    "ReferenceRequirement",
    "ShotPlan",
    "ShotSpec",
    "ShotStatus",
    "StoryboardBoardSpec",
    "StoryboardDeckSpec",
    "ShotTakeRequest",
    "TakeGenerationDefaults",
    "TakeRequestStatus",
    "TALL_OWL_BENCHMARK_ID",
    "TALL_OWL_BRAND_INPUT",
    "TALL_OWL_FIRST_FRAME_REVIEW_GUIDANCE",
    "TALL_OWL_PRODUCT_INPUT",
    "TALL_OWL_REFERENCE_ASSETS",
    "build_first_frame_review_payload",
    "build_tall_owl_first_frame_review_payload",
    "compile_shot_plan",
    "compile_tall_owl_benchmark_shot_plan",
    "get_shot_plan_preset",
    "list_shot_plan_presets",
]
